-- ==========================================
-- REBUILD DATABASE SCRIPT (v3 - Comprehensive)
-- This script will drop everything and recreate it to match the modularized code.
-- ==========================================

-- 1. DROP EVERYTHING (Clean Slate)
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

DROP FUNCTION IF EXISTS public.handle_new_user ();

DROP TABLE IF EXISTS public.teacher_students CASCADE;

DROP TABLE IF EXISTS public.teacher_classes CASCADE;

DROP TABLE IF EXISTS public.student_classes CASCADE;

DROP TABLE IF EXISTS public.attempts CASCADE;

DROP TABLE IF EXISTS public.exams CASCADE;

DROP TABLE IF EXISTS public.profiles CASCADE;

DROP TABLE IF EXISTS public.classes CASCADE;

-- 2. CREATE TABLES

-- Classes Table
CREATE TABLE public.classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    grade TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Profiles Table (Connected to Auth)
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    email TEXT,
    role TEXT DEFAULT 'student' CHECK (role IN ('admin', 'teacher', 'student')),
    full_name TEXT,
    name TEXT, -- Legacy support
    class_id BIGINT REFERENCES public.classes(id) ON DELETE SET NULL,
    class TEXT, -- Legacy support (TEXT)
    student_number TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Teacher-Class Mapping (Modularized)
CREATE TABLE public.teacher_classes (
    teacher_id UUID REFERENCES public.profiles (id) ON DELETE CASCADE,
    class_id BIGINT REFERENCES public.classes (id) ON DELETE CASCADE,
    PRIMARY KEY (teacher_id, class_id)
);

-- Student-Class Mapping (Modularized)
CREATE TABLE public.student_classes (
    student_id UUID REFERENCES public.profiles (id) ON DELETE CASCADE,
    class_id BIGINT REFERENCES public.classes (id) ON DELETE CASCADE,
    PRIMARY KEY (student_id, class_id)
);

-- Exams Table
CREATE TABLE public.exams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    passage TEXT,
    questions JSONB DEFAULT '[]'::jsonb,
    duration INTEGER DEFAULT 0,
    visibility TEXT DEFAULT 'public' CHECK (visibility IN ('public', 'private')),
    subject TEXT DEFAULT 'لغة عربية',
    author_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    engine TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Attempts Table (Results)
CREATE TABLE public.attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    exam_id BIGINT REFERENCES public.exams(id) ON DELETE CASCADE,
    subject TEXT,
    level TEXT,
    score_percentage NUMERIC,
    correct_count INTEGER DEFAULT 0,
    incorrect_count INTEGER DEFAULT 0,
    time_spent_seconds INTEGER DEFAULT 0,
    answers JSONB DEFAULT '[]'::jsonb,
    student_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Teacher-Student Linking Table (Legacy/Admin)
CREATE TABLE public.teacher_students (
    teacher_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    student_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (teacher_id, student_id)
);

-- 3. FUNCTIONS & TRIGGERS

-- Function to handle profile creation on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role, full_name, name, class_id, class, student_number)
  VALUES (
    new.id, 
    new.email, 
    COALESCE(new.raw_user_meta_data->>'role', 'student'),
    COALESCE(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', ''),
    COALESCE(new.raw_user_meta_data->>'name', new.raw_user_meta_data->>'full_name', ''),
    (CASE WHEN (new.raw_user_meta_data->>'class_id') ~ '^[0-9]+$' THEN (new.raw_user_meta_data->>'class_id')::bigint ELSE NULL END),
    COALESCE(new.raw_user_meta_data->>'class', ''),
    new.raw_user_meta_data->>'student_number'
  )
  ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    role = EXCLUDED.role,
    full_name = EXCLUDED.full_name,
    name = EXCLUDED.name,
    class_id = EXCLUDED.class_id,
    class = EXCLUDED.class,
    student_number = EXCLUDED.student_number;
    
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to call the function
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 4. ROW LEVEL SECURITY (RLS)

-- Profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read Profiles" ON public.profiles FOR
SELECT USING (true);

CREATE POLICY "Users Manage Own Profile" ON public.profiles FOR ALL USING (auth.uid () = id)
WITH
    CHECK (auth.uid () = id);

CREATE POLICY "Admin Full Access Profiles" ON public.profiles FOR ALL USING (
    (
        auth.jwt () -> 'user_metadata' ->> 'role'
    ) = 'admin'
);

-- Classes
ALTER TABLE public.classes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read Classes" ON public.classes FOR
SELECT USING (true);

CREATE POLICY "Admin Edit Classes" ON public.classes FOR ALL USING (
    (
        auth.jwt () -> 'user_metadata' ->> 'role'
    ) = 'admin'
);

-- Teacher Classes
ALTER TABLE public.teacher_classes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read Teacher Classes" ON public.teacher_classes FOR
SELECT USING (true);

CREATE POLICY "Admin Full Access Teacher Classes" ON public.teacher_classes FOR ALL USING (
    (
        auth.jwt () -> 'user_metadata' ->> 'role'
    ) = 'admin'
);

CREATE POLICY "Teachers Manage Own Classes" ON public.teacher_classes FOR ALL USING (auth.uid () = teacher_id)
WITH
    CHECK (auth.uid () = teacher_id);

-- Student Classes
ALTER TABLE public.student_classes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read Student Classes" ON public.student_classes FOR
SELECT USING (true);

CREATE POLICY "Admin Full Access Student Classes" ON public.student_classes FOR ALL USING (
    (
        auth.jwt () -> 'user_metadata' ->> 'role'
    ) = 'admin'
);

CREATE POLICY "Students Manage Own Class" ON public.student_classes FOR ALL USING (auth.uid () = student_id)
WITH
    CHECK (auth.uid () = student_id);

-- Exams
ALTER TABLE public.exams ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read Exams" ON public.exams FOR
SELECT USING (true);

CREATE POLICY "Teachers Manage Own Exams" ON public.exams FOR ALL USING (auth.uid () = author_id);

CREATE POLICY "Admin Full Access Exams" ON public.exams FOR ALL USING (
    (
        auth.jwt () -> 'user_metadata' ->> 'role'
    ) = 'admin'
);

-- Attempts
ALTER TABLE public.attempts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users Manage Own Attempts" ON public.attempts FOR ALL USING (auth.uid () = user_id)
WITH
    CHECK (auth.uid () = user_id);

CREATE POLICY "Teachers Read Student Attempts" ON public.attempts FOR
SELECT USING (
        EXISTS (
            SELECT 1
            FROM public.teacher_students
            WHERE
                teacher_id = auth.uid ()
                AND student_id = public.attempts.user_id
        )
        OR EXISTS (
            SELECT 1
            FROM public.teacher_classes tc
                JOIN public.student_classes sc ON tc.class_id = sc.class_id
            WHERE
                tc.teacher_id = auth.uid ()
                AND sc.student_id = public.attempts.user_id
        )
    );

CREATE POLICY "Admin Full Access Attempts" ON public.attempts FOR ALL USING (
    (
        auth.jwt () -> 'user_metadata' ->> 'role'
    ) = 'admin'
);

-- Teacher Students
ALTER TABLE public.teacher_students ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Teachers Manage Own Students" ON public.teacher_students FOR ALL USING (teacher_id = auth.uid ());

CREATE POLICY "Admin Full Access Teacher Students" ON public.teacher_students FOR ALL USING (
    (
        auth.jwt () -> 'user_metadata' ->> 'role'
    ) = 'admin'
);

-- 5. INITIAL DATA
INSERT INTO
    public.classes (name, grade)
VALUES ('1/1', '1'),
    ('1/2', '1'),
    ('2/1', '2'),
    ('2/2', '2'),
    ('3/1', '3'),
    ('3/2', '3'),
    ('4/1', '4'),
    ('4/2', '4'),
    ('5/1', '5'),
    ('5/2', '5');